App router fix
lihter/Movie-App pull request #13
Opened 2021-07-20 06:08 UTC by lihter

- deleted HomePageRouter
- created AppRouter which will be responsible for navigation of the whole app
- AppRouter conforms to AppRouterProtocol
- modified SceneDelegate so it calls AppRouter method to initialise the starting screen

2021-07-23 09:14 UTC, marinzg requested changes

2021-07-23 09:14 UTC, marinzg commented on MovieApp/MovieApp/AppRouter.swift
> +}
Generally, you don't need to create an extension for base protocol implementation.
Also, you want this visibility:
App/SceneDelegate -> only start the application
Everything else -> only the navigation accessible from that feature, you don't want the details screen to be able to call setInitialScreen.

For this, you don't need a protocol that will be used in App/SceneDelegate, you can just use AppRouter.

2021-07-26 13:40 UTC, lihter commented on MovieApp/MovieApp/AppRouter.swift
> +}
I deleted AppRouterProtocol.swift file and [removed it from code](https://github.com/lihter/Movie-App/pull/24/files#diff-b8e8fb675a7084dca12ae6abb54b13ee1d7293192f1e1e75308b4dca15ea5465L26) and replaced it with AppRouter where it was needed.

2021-07-27 07:18 UTC, marinzg approved these changes

2021-07-27 07:24 UTC, merged