Fetching review
lihter/Movie-App pull request #34
Opened 2021-08-04 09:56 UTC by lihter

- Created `Author` and `Review` models on every layer (client, ds, repo, use case)
- Added `fillReview` function to `MovieDetailDelegate` that will be called when the reviews are fetched
- Removed function parameter from `init()` in `ReviewView`, now the data will be given through `populate` method
- Added function for fetching reviews to every layer (client, ds, repo, use case)

![Simulator Screen Shot - iPhone 12 - 2021-08-04 at 11 42 17](https://user-images.githubusercontent.com/82365531/128159586-22cfe51a-f59e-45f9-b75d-9f849ae3ca7f.png)

2021-08-11 16:04 UTC, marinzg requested changes

2021-08-11 16:04 UTC, marinzg commented on MovieApp/MovieApp/App/Features/MovieBrowser/MoviesViewController/ViewModels/ReviewViewModel.swift
> +                                .joined(separator: "/")),
Format correctly

2021-08-11 16:04 UTC, marinzg commented on MovieApp/MovieApp/App/UseCase/MoviesUseCase.swift
> +                if reviews.count > 0 {
`guard`

2021-08-12 15:12 UTC, lihter commented on MovieApp/MovieApp/App/Features/MovieBrowser/MoviesViewController/ViewModels/ReviewViewModel.swift
> +                                .joined(separator: "/")),
[Here](https://github.com/lihter/Movie-App/pull/34/commits/7d765b025ebd89ab8c9483577954de04870bccf6#diff-fdb5e671ec0b6b557986ccda300de0696d2237a33e5b1fab3b98d7cd29d2c3fcR15-R23)

2021-08-12 15:14 UTC, lihter commented on MovieApp/MovieApp/App/UseCase/MoviesUseCase.swift
> +                if reviews.count > 0 {
[Here](https://github.com/lihter/Movie-App/pull/34/commits/7d765b025ebd89ab8c9483577954de04870bccf6#diff-88fed2adfc92bb1f90d676d6f9e69ec5d3af18a8361903c9284e6d0e70098470R83)

2021-08-12 15:47 UTC, marinzg approved these changes

2021-08-13 08:13 UTC, merged