Dealing with favorites on FavoritesVC and MovieDetailsVC
lihter/Movie-App pull request #39
Opened 2021-08-13 12:36 UTC by lihter

https://user-images.githubusercontent.com/82365531/129357408-7d3a2067-3264-4a8a-9a4c-a695d5d8aeef.mp4

2021-08-13 14:01 UTC, marinzg requested changes

2021-08-13 14:01 UTC, marinzg commented on MovieApp/MovieApp/App/Features/MovieBrowser/MoviesViewController/MovieDetail/MovieDetailPresenter.swift
> +    func checkIfFavorite() -> Bool {
This can be a computed property `isFavorite`

2021-08-13 14:01 UTC, marinzg commented on MovieApp/MovieApp/App/Repository/MovieRepository.swift
> +                .compactMap { getMovie(with: $0) }
It looks like there's an extra tab here.

2021-08-13 14:01 UTC, marinzg commented on MovieApp/MovieApp/App/Repository/MovieRepository.swift
> +    func getFavoriteMovies() -> [MovieRepoModel] {
This can be a computed property.

2021-08-16 13:03 UTC, lihter commented on MovieApp/MovieApp/App/Repository/MovieRepository.swift
> +                .compactMap { getMovie(with: $0) }
Changed later -> [here](https://github.com/lihter/Movie-App/pull/42/files#diff-119fd471623eca33515c1b8fb62109b006cbeee1e1df1dc1a8e9a2e5ba5d4c27R152)

2021-08-16 13:04 UTC, lihter commented on MovieApp/MovieApp/App/Repository/MovieRepository.swift
> +    func getFavoriteMovies() -> [MovieRepoModel] {
Changed later -> [here](https://github.com/lihter/Movie-App/pull/42/files#diff-119fd471623eca33515c1b8fb62109b006cbeee1e1df1dc1a8e9a2e5ba5d4c27R152).

2021-08-16 13:06 UTC, lihter commented on MovieApp/MovieApp/App/Features/MovieBrowser/MoviesViewController/MovieDetail/MovieDetailPresenter.swift
> +    func checkIfFavorite() -> Bool {
[Deleted old](https://github.com/lihter/Movie-App/pull/39/commits/a987714bbbc901b2b6cc70ed01ad19c4bd33c010#diff-d8a7df924093b6e29d479b7644fb3593ce7762a26b79b7f10f290852dfb0ce54L103)
[New](https://github.com/lihter/Movie-App/pull/39/commits/a987714bbbc901b2b6cc70ed01ad19c4bd33c010#diff-d8a7df924093b6e29d479b7644fb3593ce7762a26b79b7f10f290852dfb0ce54R12)

2021-08-17 11:03 UTC, fban1 approved these changes

2021-08-17 11:05 UTC, merged